name: Build Android APK
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Generate missing android/ platform folder
        run: flutter create --platforms=android .
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: poost-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
